name: tau-dev
channels:
  - defaults
  - conda-forge
  - plotly
  - pytorch
dependencies:
  - python=3.8
  - pip=20.1
  - pip:
    - shap==0.36
    - seaborn==0.11
    - networkx==2.5
    - energyflow==1.3
    - tensorflow==2.4
    - jedi==0.17.2
    - yaml
  - root=6.22
  - uproot=4.0
  - scikit-learn=0.24
  - scipy=1.5
  - statsmodels=0.12
  - plotly=4.14
  - pandas=1.1
  - numpy=1.19
  - xgboost=1.3
  - lightgbm=3.1
  - catboost=0.24
  - matplotlib=3.3
  - jupyterlab=3.0
  - ipywidgets=7.5
  - tqdm=4.55
  - cpuonly
  - pytorch=1.7
  - torchvision=0.8
  - torchaudio=0.7
  - torchtext=0.8

  
